package com.ecosystem.plugin.customer;

import com.datastax.oss.driver.api.core.CqlSession;
import org.json.JSONObject;

/**
 * This is the same structure as DefaultPreScore
 */
public class PrePredictCustomer {

    public PrePredictCustomer() {
    }

    /**
     * Pre-pre predict, after feature store is read and before dynamic and static corpora.
     */
    public void getPrePredict() {
    }

    /**
     * getPostPredict
     * @param params
     * @param session
     * @return
     */
    public static JSONObject getPrePredict(JSONObject params, CqlSession session) {

        /*
        Manipulate params that will be used by scoring and post-scoring
         */

        return params;
    }

}


/**
 * Example params: any key/value can be accessed and modified eg.

 {
  "channel" : "app",
  "uuid" : "e2ee2011-698a-4a9c-a1d0-1e61cdd5586c",
  "userid" : "ecosystem",
  "in_params" : { },
  "dbparam" : true,
  "mab" : {
    "epsilon" : 0,
    "class" : "mabone"
  },
  "mojo" : "1",
  "UPDATE" : false,
  "value" : [ "Grade12", "F", "English", 7, 2, 1, "Unmarried", 35, "Owner" ],
  "duration_paramsdb" : 4.99625,
  "resultcount" : 1,
  "lookup" : {
    "value" : 2401,
    "key" : "customer"
  },
  "explore" : 0,
  "explore_model" : 0,
  "subname" : "model",
  "whitelist" : { },
  "featuresObj" : {
    "education" : "Grade12",
    "numberOfChildren" : 2,
    "numberOfAddresses" : 1,
    "gender" : "F",
    "language" : "English",
    "numberOfProducts" : 7,
    "maritalStatus" : "Unmarried",
    "age" : 35,
    "proprtyOwnership" : "Owner"
  },
  "duration_whitelist" : 0.006667,
  "api_params" : {
    "resultcount" : 1,
    "mojo" : "1",
    "subname" : "model",
    "name" : "spend_personality",
    "subcampaign" : "model",
    "channel" : "app",
    "campaign" : "spend_personality",
    "UPDATE" : false,
    "uuid" : "e2ee2011-698a-4a9c-a1d0-1e61cdd5586c",
    "userid" : "ecosystem",
    "customer" : "2401"
  },
  "input" : [ "education", "gender", "language", "numberOfProducts", "numberOfChildren", "numberOfAddresses", "maritalStatus", "age", "proprtyOwnership" ],
  "model_selector" : {
    "model_selected" : [ 1 ]
  },
  "model_names" : {
    "GBM_1_AutoML_1_20240323_121956.zip" : 0
  },
  "name" : "spend_personality",
  "subcampaign" : "model",
  "campaign" : "spend_personality",
  "customer" : "2401",
  "default_lookup" : false
}

 */

/**
 * Example params: any key/value can be accessed and modified eg.
 * accessing and altering in_params:
 *    JSONObject in_params = params.getJSONObject("in_params"); // get params
 *    in_params.put("contextual_variable_one", ">500"); // alter or insert values
 *    in_params.put("contextual_variable_two", ">15");
 *    params.put("in_params", in_params); // place JSOBObject back in params
 *
 * {
 *   "duration_paramsdb": 3.441417,
 *   "resultcount": 4,
 *   "lookup": {
 *     "value": 27646185709,
 *     "key": "msisdn"
 *   },
 *   "explore": 0,
 *   "explore_model": 1,
 *   "subname": "none",
 *   "channel": "app",
 *   "whitelist": {
 *
 *   },
 *   "uuid": "bc5f4c0d-a429-4ddd-b34b-ecd731fde7e8",
 *   "userid": "ecosystem",
 *   "in_params": {
 *     "api_payment_method": "p",
 *     "airtime_balance": 200,
 *     "airtime_advance_limit": 30
 *   },
 *   "dbparam": true,
 *   "mab": {
 *     "epsilon": 0,
 *     "class": "mabone"
 *   },
 *   "featuresObj": {
 *     "ib_pct": 0,
 *     "data_bundle_cnt_1024_2048mb": 0,
 *     "jfu_data_bndl_count": 0,
 *     "ead_29_d": 0,
 *     "ead_06_d": 0,
 *     "j4um_bin_m1_unq_data_pch_days": 1,
 *     "subs_custm_field_c13": "",
 *     "connectu_test_locationid": "",
 *     "ead_06_v": "",
 *     "data_ib_rev": 0,
 *     "ead_29_v": "",
 *     "dmuc_ntwk_regn_nm": "Kwazulu Natal",
 *     "num_sms_l30d": 0,
 *     "num_otgng_calls_l4w": 0,
 *     "bndl_wa_val_l30": 0,
 *     "bronze_gift_id_2_accept": 0,
 *     "aa_rch_rev": 0,
 *     "bronze_gift_id_2_type": "PRIZEDRAW",
 *     "upsize_ind": "Y",
 *     "jfy_eng_ind": "NO JFY VISIT",
 *     "pzl_weights_mystery": "",
 *     "last_int_pch_dt": "1998-12-31 22:00:00.000+0000",
 *     "price_adjustment_factor": 0,
 *     "gifts_free_upsize": "{\"ShakeFree\":\"Y\",\"ShakeExtra\":\"Y\",\"ShakeVodaPay\":\"Y\"}",
 *     "sms_ib_rev": 0,
 *     "voice_active_days": 0,
 *     "bndl_phr_val_l30": 0,
 *     "mdn_data_pchs_per_day": 0,
 *     "unique_voice_alloc_days": 0,
 *     "loyalty_segment_default_ratio": 0,
 *     "data_bundle_cnt_50_250mb": 0,
 *     "customer_segment": "ST_01",
 *     "bronze_gift_id_1": "GPD_2504",
 *     "oob_voice_rev": 0,
 *     "aa_rch_pct": 0,
 *     "j4um_bin_data_spnd_pct": -1,
 *     "offnet_num_otgng_msg_l4w": 0,
 *     "bronze_gift_id_3": "G1D_500_I",
 *     "bronze_gift_id_2": "GPD_2534",
 *     "sms_alloc": 0,
 *     "jfy_abuser": "",
 *     "dmuc_suburb_nm": "Zayeka",
 *     "sms_bundl_alloc_cnt": 0,
 *     "data_advance_active_days": 0,
 *     "ead_04_d": 0,
 *     "silver_gift_id_1_type": "PRIZEDRAW",
 *     "subs_custm_field_c55": "",
 *     "subs_custm_field_c56": "",
 *     "unique_data_bundles": 0,
 *     "voice_bundle_cnt_120plus_min_ratio": "",
 *     "ead_04_v": "",
 *     "days_snc_lst_sms_pch": 100,
 *     "max_data_bndl_purch_price": "",
 *     "silver_gift_id_3": "R7D_100_I",
 *     "silver_gift_id_2": "GPD_2541",
 *     "silver_gift_id_1": "GPD_2517",
 *     "gifts_bonus": "",
 *     "pc031_80_div": 0,
 *     "gifts_free": "{\"ShakeFree\":\"RAG_108\",\"ShakeExtra\":\"GPD_2530\",\"ShakeVodaPay\":\"VCH_345\"}",
 *     "last_voice_pch_dt": "1998-12-31 22:00:00.000+0000",
 *     "acct_type_cd": "",
 *     "data_bundle_cnt_500_1024mb": 0,
 *     "ss_voice_segment": "INFLOW",
 *     "mysterypuzzletracker": "",
 *     "payment_method_code": "P",
 *     "l30_activity_flag": 0,
 *     "total_rev_l30d": 0,
 *     "most_used_cell_site_cd": "",
 *     "j4um_bin_avg_days_btw_dt_pch": 1,
 *     "avg_incm_calls_pw": 0,
 *     "minutes_l30d": 0,
 *     "int_spnd_pct": 0,
 *     "voice_bundle_cnt_0_10min": 0,
 *     "pc029_div_pc071": "",
 *     "bndl_wa_cnt_l30": 0,
 *     "silver_gift_id_2_accept": 0,
 *     "ead_02_d": 0,
 *     "j4um_bin_m1_usage": 1,
 *     "dmuc_town_nm": "Msunduzi Rural",
 *     "pc240": "",
 *     "pc120": 0,
 *     "pc241": "",
 *     "pc121": 0,
 *     "pc242": "",
 *     "pc243": "",
 *     "pc002": "",
 *     "pc244": "",
 *     "avg_outgng_calls_pw": 0,
 *     "ss_integrated_segment": "INFLOW",
 *     "paid_voice_bndl_alloc": 0,
 *     "pc114": 0,
 *     "data_usage_l30d": 0,
 *     "int_ib_mb": 0,
 *     "pc238": "",
 *     "pc118": 0,
 *     "pc239": "",
 *     "curr_2g_flg": "",
 *     "j4um_bin_avg_recharge_spnd": 1,
 *     "rt_rch_cnt": 0,
 *     "build_date": 20220519,
 *     "pc124": 0,
 *     "pc245": "",
 *     "pc246": "",
 *     "pc126": 0,
 *     "pc247": "",
 *     "payment_method_test_group": "P",
 *     "pc127": 0,
 *     "pc248": "",
 *     "pc249": "",
 *     "pc028_div_pc072_div6": "",
 *     "fi_rch_cnt": 0,
 *     "pc100": 0,
 *     "pc221": "",
 *     "curr_4g_flg": "",
 *     "pc101": "",
 *     "pc222": "",
 *     "max_voice_bndl_purch_price": "",
 *     "bndl_tckt_cnt_l30": 0,
 *     "ead_09_d": 0,
 *     "jfu_bndl_count": 0,
 *     "data_bundle_cnt_2048_5120mb": 0,
 *     "curr_price_pln_cd": "NOF7",
 *     "data_bundle_cnt_500_1024mb_ratio": "",
 *     "j4um_bin_tenure_mths_cnt": 1,
 *     "pc216": 0,
 *     "pc217": 0,
 *     "data_bundle_cnt_0_50mb_ratio": "",
 *     "ead_09_v": "",
 *     "pc230": "",
 *     "offnet_num_incm_calls_l4w": 0,
 *     "unique_voice_pch_days": 0,
 *     "bronze_gift_id_1_type": "PRIZEDRAW",
 *     "last_sms_pch_dt": "1998-12-31 22:00:00.000+0000",
 *     "pc112": 0,
 *     "fi_bndl_pct": 0,
 *     "vodabucks_bank_flg": "",
 *     "pc102": 0,
 *     "pc223": "",
 *     "voice_bundle_cnt_20_30min": 0,
 *     "pc103": 0,
 *     "pc224": "",
 *     "pc225": "",
 *     "pc226": "",
 *     "pc227": "",
 *     "pc228": "",
 *     "pc229": "",
 *     "pc160": 0,
 *     "pc281": "",
 *     "pc161": 0,
 *     "pc282": "",
 *     "pc162": 0,
 *     "pc283": "",
 *     "pc163": 0,
 *     "pc284": "",
 *     "pc164": 0,
 *     "pc285": "",
 *     "pc165": "",
 *     "pc286": "",
 *     "num_incm_calls_l4w": 0,
 *     "pc045": 0,
 *     "pc287": "",
 *     "pc046": 0,
 *     "pc288": "",
 *     "voice_bundle_cnt_10_20min": 0,
 *     "voice_ib_rev": 0,
 *     "pc280": "",
 *     "int_voice_bundl_alloc_cnt": 0,
 *     "pc279": "",
 *     "bndl_tckt_val_l30": 0,
 *     "data_bundle_cnt_1024_2048mb_ratio": "",
 *     "voice_bundle_cnt_0_10min_ratio": "",
 *     "pc173": 0,
 *     "pc174": 0,
 *     "pc054": 0,
 *     "pc175": 0,
 *     "pc055": 0,
 *     "pc176": 0,
 *     "data_active_days": 0,
 *     "pc290": "",
 *     "pc170": 0,
 *     "silver_gift_id_3_accept": 0,
 *     "vodabuck_burn_factor": 0,
 *     "data_alloc_mb": 0,
 *     "oth_rch_rev": 0,
 *     "consumer_enterprise_ind": "c",
 *     "pc289": "",
 *     "token_alloc_silver": 0,
 *     "pc048": 0,
 *     "pc169": 0,
 *     "offnet_num_otgng_calls_l4w": 0,
 *     "pc260": "",
 *     "pc261": "",
 *     "pc262": "",
 *     "pc021": 0,
 *     "pc142": 0,
 *     "pc263": "",
 *     "pc022": 0,
 *     "pc143": "",
 *     "pc264": "",
 *     "ebu_exclusion": "N",
 *     "pc023": 0,
 *     "pc144": "",
 *     "pc265": "",
 *     "pc024": 0,
 *     "pc145": 0,
 *     "pc266": "",
 *     "data_rev_status": "UNKNOWN",
 *     "bronze_gift_id_3_type": "BUNDLE",
 *     "pc136": 0,
 *     "oob_min": 0,
 *     "pc138": 0,
 *     "pc259": "",
 *     "pc139": 0,
 *     "vodapay_segment": "",
 *     "conn_day": 17,
 *     "pc150": 0,
 *     "pc151": 0,
 *     "pc031": 0,
 *     "pc032": 0,
 *     "pc033": 0,
 *     "pc035": 0,
 *     "data_advance_bndl_cnt": 0,
 *     "voice_bundle_cnt_10_20min_ratio": "",
 *     "last_rch_dt": "1998-12-31 22:00:00.000+0000",
 *     "loyalty_vb_conv_rate": 6.66666666666667,
 *     "data_bundle_cnt_250_500mb_ratio": "",
 *     "pc025": 0,
 *     "pc267": "",
 *     "pc026": 0,
 *     "pc268": "",
 *     "pc027": 0,
 *     "pc148": 0,
 *     "pc269": "",
 *     "pc028": 0,
 *     "pc149": "",
 *     "tenure_mths_cnt": 1,
 *     "data_bundle_cnt_5120mb_plus_ratio": "",
 *     "unique_data_alloc_days": 0,
 *     "pc086": 0,
 *     "subs_id": 723632880,
 *     "pc080": 0,
 *     "unique_integrated_bundles": 0,
 *     "mdn_voice_pchs_per_day": 0,
 *     "offnet_num_incm_msg_l4w": 0,
 *     "j4um_bin_m1_data_active_days": 1,
 *     "voice_spnd_pct": 0,
 *     "dmuc_prov_nm": "Kwazulu-Natal",
 *     "rt_rch_rev": 0,
 *     "voice_bundle_cnt_120plus_min": 0,
 *     "num_active_days": 0,
 *     "pc094": 0,
 *     "pc097": 0,
 *     "rt_rch_days": 0,
 *     "rchgs_cnt_l30": 0,
 *     "pc091": 0,
 *     "pc092": 0,
 *     "days_snc_lst_data_pch": 100,
 *     "ead_20_d": 0,
 *     "conn_dt": "",
 *     "avg_recharge_spnd": 0,
 *     "avg_voice_bndl_spnd": 0,
 *     "fi_rch_pct": 0,
 *     "pc183": 0,
 *     "jfu_data_content_recs": "",
 *     "pc185": 0,
 *     "pc186": 0,
 *     "ead_20_v": "",
 *     "pc187": 0,
 *     "pc189": 0,
 *     "oth_rch_cnt": 0,
 *     "mdn_days_btw_dt_pch": 0,
 *     "stretch_factor": 0.2,
 *     "pc072": 0,
 *     "pc193": 0,
 *     "pc194": "",
 *     "pc195": "",
 *     "pc196": "",
 *     "pc197": "",
 *     "data_bundle_cnt_5120mb_plus": 0,
 *     "pc198": "",
 *     "pc199": "",
 *     "days_snc_lst_voice_pch": 100,
 *     "data_usg_status": "UNKNOWN",
 *     "pc191": 0,
 *     "aa_rch_days": 0,
 *     "pc192": 0,
 *     "loyalty_segment": "GEN_00001",
 *     "pc028_add_pc031_div_pc086": "",
 *     "fi_rch_rev": 0,
 *     "j4um_bin_avg_data_bndl_spnd": 1,
 *     "fi_data_ib_rev": 0,
 *     "mdn_days_btw_int_pch": 0,
 *     "voice_usg_status": "UNKNOWN",
 *     "days_snc_lst_int_pch": 100,
 *     "data_burn_rate": 0,
 *     "data_bundl_alloc_cnt": 0,
 *     "int_data_bundl_alloc_cnt": 0,
 *     "url_usage_pct": 0,
 *     "avg_fi_spnd": 0,
 *     "ib_min": 0,
 *     "mdn_days_btw_voice_pch": 0,
 *     "silver_gift_id_2_type": "PRIZEDRAW",
 *     "pmt_meth_cd": "P",
 *     "voice_bundle_cnt_20_30min_ratio": "",
 *     "pc028_div_pc072": "",
 *     "subs_puzzle_cycle": "",
 *     "pzl_weights_grand": "",
 *     "avg_int_bndl_spnd": 0,
 *     "voice_bundle_cnt_60_120min": 0,
 *     "data_bundle_cnt_0_50mb": 0,
 *     "daily_data_usage_avg": 0,
 *     "avg_rt_spnd": 0,
 *     "num_incm_msg_l4w": 0,
 *     "unique_data_pch_days": 0,
 *     "j4um_bin_avg_data_alloc": 1,
 *     "pc031_div_pc080": "",
 *     "jfu_ratio": 0,
 *     "tot_calls": 0,
 *     "jfu_data_bndl_rev": 0,
 *     "vodabucks_gift_secondary": "",
 *     "vodabuck_conversion_rate": 0.1,
 *     "weekly_vodapay_limited_offr_purchases": "",
 *     "gifts_free_tokens": "{\"ShakeFree\":0.0,\"ShakeExtra\":0.0,\"ShakeVodaPay\":0.0,\"ShakeMega\":10.0,\"ShakeDaily\":10.0}",
 *     "bronze_gift_id_1_accept": 0,
 *     "num_otgng_msg_l4w": 0,
 *     "int_data_alloc_mb": 0,
 *     "oob_data_rev": 0,
 *     "j4um_bin_d_na_m1": 1,
 *     "data_spnd_pct": 0,
 *     "jfu_voice_bndl_cnt": 0,
 *     "vodapay_segment_limits": "",
 *     "daily_voice_usage_avg": 0,
 *     "last_data_pch_dt": "1998-12-31 22:00:00.000+0000",
 *     "gsm_tactical_offer": "",
 *     "gsm_white_list": "{\"GSM_12_DO1\",\"GSM_22_DO1\",\"GSM_1008_DO1\",\"GSM_36_DO1\",\"GSM_42_DO1\",\"GSM_38_DO1\",\"GSM_29_DO1\",\"GSM_999_DO1\",\"GSM_1105_DO1\"}",
 *     "last_active_dt": "1998-12-31 22:00:00.000+0000",
 *     "ead_13_d": 0,
 *     "ead_02_v": "",
 *     "voice_bundle_cnt_60_120min_ratio": "",
 *     "msisdn_range": 9,
 *     "omega": 0,
 *     "data_bundle_cnt_250_500mb": 0,
 *     "ead_01_d": 0,
 *     "all_revenue_inc_vat": 0,
 *     "ead_13_v": "",
 *     "int_voice_alloc_mins": 0,
 *     "cg_uid": "CG_43",
 *     "pc091_add_pc092": "",
 *     "voice_bundle_cnt_30_45min_ratio": "",
 *     "dmuc_cell_site_cd": "KZN_59301",
 *     "connected_days": "",
 *     "ead_01_v": "",
 *     "voice_bundle_cnt_30_45min": 0,
 *     "pd_uid": "CG_43",
 *     "active_day_segment": "Data Unkwn",
 *     "voice_bundl_alloc_cnt": 0,
 *     "unique_sms_pch_days": 0,
 *     "unique_integrated_pch_days": 0,
 *     "ss_data_segment": "",
 *     "data_bundle_cnt_2048_5120mb_ratio": "",
 *     "vodapay_limited_offr_purchases": "",
 *     "bndl_phr_cnt_l30": 0,
 *     "data_bundle_cnt_50_250mb_ratio": "",
 *     "mdn_int_pchs_per_day": 0,
 *     "voice_bundle_cnt_45_60min": 0,
 *     "bronze_gift_id_3_accept": 0,
 *     "ead_00_d": 0,
 *     "unique_sms_bundles": 0,
 *     "rchgs_val_l30": 0,
 *     "vodabucks_gift_primary": "",
 *     "jfu_all_bndl_rev": 0,
 *     "voice_alloc_mins": 0,
 *     "voice_burn_rate": 0,
 *     "voice_bundle_cnt_45_60min_ratio": "",
 *     "ead_00_v": "",
 *     "voice_rev_status": "UNKNOWN",
 *     "token_alloc_bronze": 0,
 *     "device_type": "",
 *     "unique_voice_bundles": 0,
 *     "fi_voice_ib_rev": 0,
 *     "ib_mb": 0,
 *     "avg_subs_rvnu_amt": 0,
 *     "pcnt_offnet_out_calls_l4w": 0,
 *     "silver_gift_id_3_type": "BUNDLE",
 *     "jfu_voice_bndl_rev": 0,
 *     "puzzletracker": "",
 *     "avg_oth_spnd": 0,
 *     "pcnt_inc_calls_l4w": 0,
 *     "silver_gift_id_1_accept": 0,
 *     "voice_behav_seg": "UNKNOWN",
 *     "int_ib_min": 0,
 *     "bundle_usage_segment": "",
 *     "integrated_ib_rev": 0,
 *     "oob_mb": 0,
 *     "oth_rch_days": 0,
 *     "data_behav_seg": "UNKNOWN",
 *     "tenure_group": "Inflow",
 *     "aa_rch_cnt": 0,
 *     "data_adv_rev": 0,
 *     "price_pln_type_desc": "Prepaid",
 *     "days_snc_lst_actvy": 999,
 *     "avg_aa_spnd": 0,
 *     "avg_data_bndl_spnd": 0,
 *     "fi_rch_days": 0,
 *     "j4um_bin_avg_data_pchs_per_day": -1,
 *     "integrated_bundl_alloc_cnt": 0,
 *     "curr_3g_flg": "",
 *     "paid_data_bndl_alloc_cnt": 0
 *   },
 *   "duration_whitelist": 0.006292,
 *   "api_params": {
 *     "resultcount": 4,
 *     "subname": "none",
 *     "name": "just4u",
 *     "subcampaign": "none",
 *     "channel": "app",
 *     "uuid": "bc5f4c0d-a429-4ddd-b34b-ecd731fde7e8",
 *     "userid": "ecosystem",
 *     "customer": "27646185709"
 *   },
 *   "input": [
 *     "aa_rch_cnt",
 *     "aa_rch_days",
 *     "aa_rch_pct",
 *     "aa_rch_rev",
 *     "acct_type_cd",
 *     "active_day_segment",
 *     "all_revenue_inc_vat",
 *     "avg_aa_spnd",
 *     "avg_data_bndl_spnd",
 *     "avg_fi_spnd",
 *     "avg_incm_calls_pw",
 *     "avg_int_bndl_spnd",
 *     "avg_oth_spnd",
 *     "avg_outgng_calls_pw",
 *     "avg_recharge_spnd",
 *     "avg_rt_spnd",
 *     "avg_subs_rvnu_amt",
 *     "avg_voice_bndl_spnd",
 *     "bndl_phr_cnt_l30",
 *     "bndl_phr_val_l30",
 *     "bndl_tckt_cnt_l30",
 *     "bndl_tckt_val_l30",
 *     "bndl_wa_cnt_l30",
 *     "bndl_wa_val_l30",
 *     "bronze_gift_id_1",
 *     "bronze_gift_id_1_accept",
 *     "bronze_gift_id_1_type",
 *     "bronze_gift_id_2",
 *     "bronze_gift_id_2_accept",
 *     "bronze_gift_id_2_type",
 *     "bronze_gift_id_3",
 *     "bronze_gift_id_3_accept",
 *     "bronze_gift_id_3_type",
 *     "build_date",
 *     "bundle_usage_segment",
 *     "cg_uid",
 *     "conn_day",
 *     "conn_dt",
 *     "connected_days",
 *     "connectu_test_locationid",
 *     "consumer_enterprise_ind",
 *     "curr_2g_flg",
 *     "curr_3g_flg",
 *     "curr_4g_flg",
 *     "curr_price_pln_cd",
 *     "customer_segment",
 *     "daily_data_usage_avg",
 *     "daily_voice_usage_avg",
 *     "data_active_days",
 *     "data_adv_rev",
 *     "data_advance_active_days",
 *     "data_advance_bndl_cnt",
 *     "data_alloc_mb",
 *     "data_behav_seg",
 *     "data_bundl_alloc_cnt",
 *     "data_bundle_cnt_0_50mb",
 *     "data_bundle_cnt_0_50mb_ratio",
 *     "data_bundle_cnt_1024_2048mb",
 *     "data_bundle_cnt_1024_2048mb_ratio",
 *     "data_bundle_cnt_2048_5120mb",
 *     "data_bundle_cnt_2048_5120mb_ratio",
 *     "data_bundle_cnt_250_500mb",
 *     "data_bundle_cnt_250_500mb_ratio",
 *     "data_bundle_cnt_500_1024mb",
 *     "data_bundle_cnt_500_1024mb_ratio",
 *     "data_bundle_cnt_50_250mb",
 *     "data_bundle_cnt_50_250mb_ratio",
 *     "data_bundle_cnt_5120mb_plus",
 *     "data_bundle_cnt_5120mb_plus_ratio",
 *     "data_burn_rate",
 *     "data_ib_rev",
 *     "data_rev_status",
 *     "data_spnd_pct",
 *     "data_usage_l30d",
 *     "data_usg_status",
 *     "days_snc_lst_actvy",
 *     "days_snc_lst_data_pch",
 *     "days_snc_lst_int_pch",
 *     "days_snc_lst_sms_pch",
 *     "days_snc_lst_voice_pch",
 *     "device_type",
 *     "dmuc_cell_site_cd",
 *     "dmuc_ntwk_regn_nm",
 *     "dmuc_prov_nm",
 *     "dmuc_suburb_nm",
 *     "dmuc_town_nm",
 *     "ead_00_d",
 *     "ead_00_v",
 *     "ead_01_d",
 *     "ead_01_v",
 *     "ead_02_d",
 *     "ead_02_v",
 *     "ead_04_d",
 *     "ead_04_v",
 *     "ead_06_d",
 *     "ead_06_v",
 *     "ead_09_d",
 *     "ead_09_v",
 *     "ead_13_d",
 *     "ead_13_v",
 *     "ead_20_d",
 *     "ead_20_v",
 *     "ead_29_d",
 *     "ead_29_v",
 *     "ebu_exclusion",
 *     "fi_bndl_pct",
 *     "fi_data_ib_rev",
 *     "fi_rch_cnt",
 *     "fi_rch_days",
 *     "fi_rch_pct",
 *     "fi_rch_rev",
 *     "fi_voice_ib_rev",
 *     "gifts_bonus",
 *     "gifts_free",
 *     "gifts_free_tokens",
 *     "gifts_free_upsize",
 *     "gsm_tactical_offer",
 *     "gsm_white_list",
 *     "ib_mb",
 *     "ib_min",
 *     "ib_pct",
 *     "int_data_alloc_mb",
 *     "int_data_bundl_alloc_cnt",
 *     "int_ib_mb",
 *     "int_ib_min",
 *     "int_spnd_pct",
 *     "int_voice_alloc_mins",
 *     "int_voice_bundl_alloc_cnt",
 *     "integrated_bundl_alloc_cnt",
 *     "integrated_ib_rev",
 *     "j4um_bin_avg_data_alloc",
 *     "j4um_bin_avg_data_bndl_spnd",
 *     "j4um_bin_avg_data_pchs_per_day",
 *     "j4um_bin_avg_days_btw_dt_pch",
 *     "j4um_bin_avg_recharge_spnd",
 *     "j4um_bin_d_na_m1",
 *     "j4um_bin_data_spnd_pct",
 *     "j4um_bin_m1_data_active_days",
 *     "j4um_bin_m1_unq_data_pch_days",
 *     "j4um_bin_m1_usage",
 *     "j4um_bin_tenure_mths_cnt",
 *     "jfu_all_bndl_rev",
 *     "jfu_bndl_count",
 *     "jfu_data_bndl_count",
 *     "jfu_data_bndl_rev",
 *     "jfu_data_content_recs",
 *     "jfu_ratio",
 *     "jfu_voice_bndl_cnt",
 *     "jfu_voice_bndl_rev",
 *     "jfy_abuser",
 *     "jfy_eng_ind",
 *     "l30_activity_flag",
 *     "last_active_dt",
 *     "last_data_pch_dt",
 *     "last_int_pch_dt",
 *     "last_rch_dt",
 *     "last_sms_pch_dt",
 *     "last_voice_pch_dt",
 *     "loyalty_segment",
 *     "loyalty_segment_default_ratio",
 *     "loyalty_vb_conv_rate",
 *     "max_data_bndl_purch_price",
 *     "max_voice_bndl_purch_price",
 *     "mdn_data_pchs_per_day",
 *     "mdn_days_btw_dt_pch",
 *     "mdn_days_btw_int_pch",
 *     "mdn_days_btw_voice_pch",
 *     "mdn_int_pchs_per_day",
 *     "mdn_voice_pchs_per_day",
 *     "minutes_l30d",
 *     "most_used_cell_site_cd",
 *     "msisdn_range",
 *     "mysterypuzzletracker",
 *     "num_active_days",
 *     "num_incm_calls_l4w",
 *     "num_incm_msg_l4w",
 *     "num_otgng_calls_l4w",
 *     "num_otgng_msg_l4w",
 *     "num_sms_l30d",
 *     "offnet_num_incm_calls_l4w",
 *     "offnet_num_incm_msg_l4w",
 *     "offnet_num_otgng_calls_l4w",
 *     "offnet_num_otgng_msg_l4w",
 *     "omega",
 *     "oob_data_rev",
 *     "oob_mb",
 *     "oob_min",
 *     "oob_voice_rev",
 *     "oth_rch_cnt",
 *     "oth_rch_days",
 *     "oth_rch_rev",
 *     "paid_data_bndl_alloc_cnt",
 *     "paid_voice_bndl_alloc",
 *     "payment_method_code",
 *     "payment_method_test_group",
 *     "pc002",
 *     "pc021",
 *     "pc022",
 *     "pc023",
 *     "pc024",
 *     "pc025",
 *     "pc026",
 *     "pc027",
 *     "pc028",
 *     "pc028_add_pc031_div_pc086",
 *     "pc028_div_pc072",
 *     "pc028_div_pc072_div6",
 *     "pc029_div_pc071",
 *     "pc031",
 *     "pc031_80_div",
 *     "pc031_div_pc080",
 *     "pc032",
 *     "pc033",
 *     "pc035",
 *     "pc045",
 *     "pc046",
 *     "pc048",
 *     "pc054",
 *     "pc055",
 *     "pc072",
 *     "pc080",
 *     "pc086",
 *     "pc091",
 *     "pc091_add_pc092",
 *     "pc092",
 *     "pc094",
 *     "pc097",
 *     "pc100",
 *     "pc101",
 *     "pc102",
 *     "pc103",
 *     "pc112",
 *     "pc114",
 *     "pc118",
 *     "pc120",
 *     "pc121",
 *     "pc124",
 *     "pc126",
 *     "pc127",
 *     "pc136",
 *     "pc138",
 *     "pc139",
 *     "pc142",
 *     "pc143",
 *     "pc144",
 *     "pc145",
 *     "pc148",
 *     "pc149",
 *     "pc150",
 *     "pc151",
 *     "pc160",
 *     "pc161",
 *     "pc162",
 *     "pc163",
 *     "pc164",
 *     "pc165",
 *     "pc169",
 *     "pc170",
 *     "pc173",
 *     "pc174",
 *     "pc175",
 *     "pc176",
 *     "pc183",
 *     "pc185",
 *     "pc186",
 *     "pc187",
 *     "pc189",
 *     "pc191",
 *     "pc192",
 *     "pc193",
 *     "pc194",
 *     "pc195",
 *     "pc196",
 *     "pc197",
 *     "pc198",
 *     "pc199",
 *     "pc216",
 *     "pc217",
 *     "pc221",
 *     "pc222",
 *     "pc223",
 *     "pc224",
 *     "pc225",
 *     "pc226",
 *     "pc227",
 *     "pc228",
 *     "pc229",
 *     "pc230",
 *     "pc238",
 *     "pc239",
 *     "pc240",
 *     "pc241",
 *     "pc242",
 *     "pc243",
 *     "pc244",
 *     "pc245",
 *     "pc246",
 *     "pc247",
 *     "pc248",
 *     "pc249",
 *     "pc259",
 *     "pc260",
 *     "pc261",
 *     "pc262",
 *     "pc263",
 *     "pc264",
 *     "pc265",
 *     "pc266",
 *     "pc267",
 *     "pc268",
 *     "pc269",
 *     "pc279",
 *     "pc280",
 *     "pc281",
 *     "pc282",
 *     "pc283",
 *     "pc284",
 *     "pc285",
 *     "pc286",
 *     "pc287",
 *     "pc288",
 *     "pc289",
 *     "pc290",
 *     "pcnt_inc_calls_l4w",
 *     "pcnt_offnet_out_calls_l4w",
 *     "pd_uid",
 *     "pmt_meth_cd",
 *     "price_adjustment_factor",
 *     "price_pln_type_desc",
 *     "puzzletracker",
 *     "pzl_weights_grand",
 *     "pzl_weights_mystery",
 *     "rchgs_cnt_l30",
 *     "rchgs_val_l30",
 *     "rt_rch_cnt",
 *     "rt_rch_days",
 *     "rt_rch_rev",
 *     "silver_gift_id_1",
 *     "silver_gift_id_1_accept",
 *     "silver_gift_id_1_type",
 *     "silver_gift_id_2",
 *     "silver_gift_id_2_accept",
 *     "silver_gift_id_2_type",
 *     "silver_gift_id_3",
 *     "silver_gift_id_3_accept",
 *     "silver_gift_id_3_type",
 *     "sms_alloc",
 *     "sms_bundl_alloc_cnt",
 *     "sms_ib_rev",
 *     "ss_data_segment",
 *     "ss_integrated_segment",
 *     "ss_voice_segment",
 *     "stretch_factor",
 *     "subs_custm_field_c13",
 *     "subs_custm_field_c55",
 *     "subs_custm_field_c56",
 *     "subs_id",
 *     "subs_puzzle_cycle",
 *     "tenure_group",
 *     "tenure_mths_cnt",
 *     "token_alloc_bronze",
 *     "token_alloc_silver",
 *     "tot_calls",
 *     "total_rev_l30d",
 *     "unique_data_alloc_days",
 *     "unique_data_bundles",
 *     "unique_data_pch_days",
 *     "unique_integrated_bundles",
 *     "unique_integrated_pch_days",
 *     "unique_sms_bundles",
 *     "unique_sms_pch_days",
 *     "unique_voice_alloc_days",
 *     "unique_voice_bundles",
 *     "unique_voice_pch_days",
 *     "upsize_ind",
 *     "url_usage_pct",
 *     "vodabuck_burn_factor",
 *     "vodabuck_conversion_rate",
 *     "vodabucks_bank_flg",
 *     "vodabucks_gift_primary",
 *     "vodabucks_gift_secondary",
 *     "vodapay_limited_offr_purchases",
 *     "vodapay_segment",
 *     "vodapay_segment_limits",
 *     "voice_active_days",
 *     "voice_alloc_mins",
 *     "voice_behav_seg",
 *     "voice_bundl_alloc_cnt",
 *     "voice_bundle_cnt_0_10min",
 *     "voice_bundle_cnt_0_10min_ratio",
 *     "voice_bundle_cnt_10_20min",
 *     "voice_bundle_cnt_10_20min_ratio",
 *     "voice_bundle_cnt_120plus_min",
 *     "voice_bundle_cnt_120plus_min_ratio",
 *     "voice_bundle_cnt_20_30min",
 *     "voice_bundle_cnt_20_30min_ratio",
 *     "voice_bundle_cnt_30_45min",
 *     "voice_bundle_cnt_30_45min_ratio",
 *     "voice_bundle_cnt_45_60min",
 *     "voice_bundle_cnt_45_60min_ratio",
 *     "voice_bundle_cnt_60_120min",
 *     "voice_bundle_cnt_60_120min_ratio",
 *     "voice_burn_rate",
 *     "voice_ib_rev",
 *     "voice_rev_status",
 *     "voice_spnd_pct",
 *     "voice_usg_status",
 *     "weekly_vodapay_limited_offr_purchases"
 *   ],
 *   "model_selector": {
 *     "model_selected": [
 *       1
 *     ]
 *   },
 *   "mojo": "1",
 *   "name": "just4u",
 *   "subcampaign": "none",
 *   "value": [
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     "Data Unkwn",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "GPD_2504",
 *     0,
 *     "PRIZEDRAW",
 *     "GPD_2534",
 *     0,
 *     "PRIZEDRAW",
 *     "G1D_500_I",
 *     0,
 *     "BUNDLE",
 *     20220519,
 *     "",
 *     "CG_43",
 *     17,
 *     "",
 *     "",
 *     "",
 *     "c",
 *     "",
 *     "",
 *     "",
 *     "NOF7",
 *     "ST_01",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "UNKNOWN",
 *     0,
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     0,
 *     "UNKNOWN",
 *     0,
 *     0,
 *     "UNKNOWN",
 *     999,
 *     100,
 *     100,
 *     100,
 *     100,
 *     "",
 *     "KZN_59301",
 *     "Kwazulu Natal",
 *     "Kwazulu-Natal",
 *     "Zayeka",
 *     "Msunduzi Rural",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     "N",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     "{\"ShakeFree\":\"RAG_108\",\"ShakeExtra\":\"GPD_2530\",\"ShakeVodaPay\":\"VCH_345\"}",
 *     "{\"ShakeFree\":0.0,\"ShakeExtra\":0.0,\"ShakeVodaPay\":0.0,\"ShakeMega\":10.0,\"ShakeDaily\":10.0}",
 *     "{\"ShakeFree\":\"Y\",\"ShakeExtra\":\"Y\",\"ShakeVodaPay\":\"Y\"}",
 *     "",
 *     "{\"GSM_12_DO1\",\"GSM_22_DO1\",\"GSM_1008_DO1\",\"GSM_36_DO1\",\"GSM_42_DO1\",\"GSM_38_DO1\",\"GSM_29_DO1\",\"GSM_999_DO1\",\"GSM_1105_DO1\"}",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     1,
 *     1,
 *     -1,
 *     1,
 *     1,
 *     1,
 *     -1,
 *     1,
 *     1,
 *     1,
 *     1,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     "",
 *     "NO JFY VISIT",
 *     0,
 *     "1998-12-31 22:00:00.000+0000",
 *     "1998-12-31 22:00:00.000+0000",
 *     "1998-12-31 22:00:00.000+0000",
 *     "1998-12-31 22:00:00.000+0000",
 *     "1998-12-31 22:00:00.000+0000",
 *     "1998-12-31 22:00:00.000+0000",
 *     "GEN_00001",
 *     0,
 *     6.66666666666667,
 *     "",
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     9,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "P",
 *     "P",
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     "",
 *     "",
 *     "",
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     "",
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     0,
 *     0,
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     0,
 *     0,
 *     "CG_43",
 *     "P",
 *     0,
 *     "Prepaid",
 *     "",
 *     "",
 *     "",
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "GPD_2517",
 *     0,
 *     "PRIZEDRAW",
 *     "GPD_2541",
 *     0,
 *     "PRIZEDRAW",
 *     "R7D_100_I",
 *     0,
 *     "BUNDLE",
 *     0,
 *     0,
 *     0,
 *     "",
 *     "INFLOW",
 *     "INFLOW",
 *     0.2,
 *     "",
 *     "",
 *     "",
 *     723632880,
 *     "",
 *     "Inflow",
 *     1,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     0,
 *     "Y",
 *     0,
 *     0,
 *     0.1,
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     "",
 *     0,
 *     0,
 *     "UNKNOWN",
 *     0,
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     "",
 *     0,
 *     0,
 *     "UNKNOWN",
 *     0,
 *     "UNKNOWN",
 *     ""
 *   ],
 *   "customer": "27646185709",
 *   "default_lookup": false
 * }
 */